// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_javax_crypto_mode_CBC__
#define __gnu_javax_crypto_mode_CBC__

#pragma interface

#include <gnu/javax/crypto/mode/BaseMode.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace javax
    {
      namespace crypto
      {
        namespace mode
        {
          class CBC;
        }
        namespace cipher
        {
          class IBlockCipher;
        }
      }
    }
  }
}

class gnu::javax::crypto::mode::CBC : public ::gnu::javax::crypto::mode::BaseMode
{
public: // actually package-private
  CBC (::gnu::javax::crypto::cipher::IBlockCipher *, jint);
private:
  CBC (::gnu::javax::crypto::mode::CBC *);
public:
  virtual ::java::lang::Object *clone ();
  virtual void setup ();
  virtual void teardown ();
  virtual void encryptBlock (jbyteArray, jint, jbyteArray, jint);
  virtual void decryptBlock (jbyteArray, jint, jbyteArray, jint);
private:
  jbyteArray __attribute__((aligned(__alignof__( ::gnu::javax::crypto::mode::BaseMode ))))  lastBlock;
  jbyteArray scratch;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_javax_crypto_mode_CBC__ */
