// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_javax_crypto_keyring_PasswordAuthenticatedEntry__
#define __gnu_javax_crypto_keyring_PasswordAuthenticatedEntry__

#pragma interface

#include <gnu/javax/crypto/keyring/MaskableEnvelopeEntry.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace javax
    {
      namespace crypto
      {
        namespace mac
        {
          class IMac;
        }
        namespace keyring
        {
          class PasswordAuthenticatedEntry;
          class Properties;
        }
      }
    }
  }
}

class gnu::javax::crypto::keyring::PasswordAuthenticatedEntry : public ::gnu::javax::crypto::keyring::MaskableEnvelopeEntry
{
public:
  PasswordAuthenticatedEntry (::java::lang::String *, jint, ::gnu::javax::crypto::keyring::Properties *);
private:
  PasswordAuthenticatedEntry ();
public:
  static ::gnu::javax::crypto::keyring::PasswordAuthenticatedEntry *decode (::java::io::DataInputStream *, jcharArray);
  static ::gnu::javax::crypto::keyring::PasswordAuthenticatedEntry *decode (::java::io::DataInputStream *);
  virtual void verify (jcharArray);
  virtual void authenticate (jcharArray);
  virtual void encode (::java::io::DataOutputStream *, jcharArray);
public:  // actually protected
  virtual void encodePayload (::java::io::DataOutputStream *);
private:
  ::gnu::javax::crypto::mac::IMac *getMac (jcharArray);
  static ::java::util::logging::Logger *log;
public:
  static const jint TYPE = 3L;

  static ::java::lang::Class class$;
};

#endif /* __gnu_javax_crypto_keyring_PasswordAuthenticatedEntry__ */
