// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_javax_crypto_assembly_LoopbackTransformer__
#define __gnu_javax_crypto_assembly_LoopbackTransformer__

#pragma interface

#include <gnu/javax/crypto/assembly/Transformer.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace javax
    {
      namespace crypto
      {
        namespace assembly
        {
          class LoopbackTransformer;
        }
      }
    }
  }
}

class gnu::javax::crypto::assembly::LoopbackTransformer : public ::gnu::javax::crypto::assembly::Transformer
{
public: // actually package-private
  LoopbackTransformer ();
public:
  virtual void init (::java::util::Map *) { }
  virtual void reset () { }
  virtual jbyteArray update (jbyteArray, jint, jint);
  virtual jbyteArray lastUpdate ();
public: // actually package-private
  virtual void initDelegate (::java::util::Map *) { }
  virtual jint delegateBlockSize ();
  virtual void resetDelegate () { }
  virtual jbyteArray updateDelegate (jbyteArray, jint, jint);
  virtual jbyteArray lastUpdateDelegate ();
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_javax_crypto_assembly_LoopbackTransformer__ */
