// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_java_awt_color_PyccConverter__
#define __gnu_java_awt_color_PyccConverter__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace java
    {
      namespace awt
      {
        namespace color
        {
          class PyccConverter;
        }
      }
    }
  }
}

class gnu::java::awt::color::PyccConverter : public ::java::lang::Object
{
public:
  virtual jfloatArray toRGB (jfloatArray) { return 0; }
  virtual jfloatArray fromRGB (jfloatArray) { return 0; }
  virtual jfloatArray toCIEXYZ (jfloatArray) { return 0; }
  virtual jfloatArray fromCIEXYZ (jfloatArray) { return 0; }
  PyccConverter ();

  static ::java::lang::Class class$;
};

#endif /* __gnu_java_awt_color_PyccConverter__ */
