// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_crypto_interfaces_DHPrivateKey__
#define __javax_crypto_interfaces_DHPrivateKey__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace crypto
    {
      namespace interfaces
      {
        class DHPrivateKey;
      }
    }
  }
  namespace java
  {
    namespace math
    {
      class BigInteger;
    }
  }
}

class javax::crypto::interfaces::DHPrivateKey : public ::java::lang::Object
{
public:
  virtual ::java::math::BigInteger *getX () = 0;
  static const jlong serialVersionUID = 2211791113380396553LL;

  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif /* __javax_crypto_interfaces_DHPrivateKey__ */
