// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_crypto_KeyAgreement__
#define __javax_crypto_KeyAgreement__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace java
  {
    namespace security
    {
      namespace spec
      {
        class AlgorithmParameterSpec;
      }
      class SecureRandom;
      class Key;
      class Provider;
    }
  }
  namespace javax
  {
    namespace crypto
    {
      class SecretKey;
      class KeyAgreement;
      class KeyAgreementSpi;
    }
  }
}

class javax::crypto::KeyAgreement : public ::java::lang::Object
{
public:  // actually protected
  KeyAgreement (::javax::crypto::KeyAgreementSpi *, ::java::security::Provider *, ::java::lang::String *);
public:
  static ::javax::crypto::KeyAgreement *getInstance (::java::lang::String *);
  static ::javax::crypto::KeyAgreement *getInstance (::java::lang::String *, ::java::lang::String *);
  static ::javax::crypto::KeyAgreement *getInstance (::java::lang::String *, ::java::security::Provider *);
  virtual ::java::security::Key *doPhase (::java::security::Key *, jboolean);
  virtual jbyteArray generateSecret ();
  virtual jint generateSecret (jbyteArray, jint);
  virtual ::javax::crypto::SecretKey *generateSecret (::java::lang::String *);
  virtual ::java::lang::String *getAlgorithm () { return algorithm; }
  virtual ::java::security::Provider *getProvider () { return provider; }
  virtual void init (::java::security::Key *);
  virtual void init (::java::security::Key *, ::java::security::SecureRandom *);
  virtual void init (::java::security::Key *, ::java::security::spec::AlgorithmParameterSpec *);
  virtual void init (::java::security::Key *, ::java::security::spec::AlgorithmParameterSpec *, ::java::security::SecureRandom *);
private:
  static ::java::lang::String *SERVICE;
  ::javax::crypto::KeyAgreementSpi * __attribute__((aligned(__alignof__( ::java::lang::Object )))) kaSpi;
  ::java::security::Provider *provider;
  ::java::lang::String *algorithm;
  jboolean virgin;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_crypto_KeyAgreement__ */
