// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_javax_crypto_key_srp6_SRP6SaslServer__
#define __gnu_javax_crypto_key_srp6_SRP6SaslServer__

#pragma interface

#include <gnu/javax/crypto/key/srp6/SRP6TLSServer.h>

extern "Java"
{
  namespace gnu
  {
    namespace javax
    {
      namespace crypto
      {
        namespace key
        {
          namespace srp6
          {
            class SRP6SaslServer;
          }
          class OutgoingMessage;
          class IncomingMessage;
        }
      }
    }
  }
}

class gnu::javax::crypto::key::srp6::SRP6SaslServer : public ::gnu::javax::crypto::key::srp6::SRP6TLSServer
{
public:  // actually protected
  virtual ::gnu::javax::crypto::key::OutgoingMessage *computeSharedSecret (::gnu::javax::crypto::key::IncomingMessage *);
public:
  SRP6SaslServer ();

  static ::java::lang::Class class$;
};

#endif /* __gnu_javax_crypto_key_srp6_SRP6SaslServer__ */
