// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_nio_ShortBufferImpl__
#define __java_nio_ShortBufferImpl__

#pragma interface

#include <java/nio/ShortBuffer.h>
#include <gcj/array.h>

extern "Java"
{
  namespace java
  {
    namespace nio
    {
      class ShortBufferImpl;
      class ByteOrder;
      class ShortBuffer;
    }
  }
}

class java::nio::ShortBufferImpl : public ::java::nio::ShortBuffer
{
public: // actually package-private
  ShortBufferImpl (jint);
  ShortBufferImpl (jshortArray, jint, jint, jint, jint, jint, jboolean);
public:
  virtual jboolean isReadOnly () { return readOnly; }
  virtual ::java::nio::ShortBuffer *slice ();
  virtual ::java::nio::ShortBuffer *duplicate ();
  virtual ::java::nio::ShortBuffer *asReadOnlyBuffer ();
  virtual ::java::nio::ShortBuffer *compact ();
  virtual jboolean isDirect ();
  virtual jshort get ();
  virtual ::java::nio::ShortBuffer *put (jshort);
  virtual jshort get (jint);
  virtual ::java::nio::ShortBuffer *put (jint, jshort);
  virtual ::java::nio::ByteOrder *order ();
private:
  jboolean __attribute__((aligned(__alignof__( ::java::nio::ShortBuffer ))))  readOnly;
public:

  static ::java::lang::Class class$;
};

#endif /* __java_nio_ShortBufferImpl__ */
