// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_java_security_hash_RipeMD160__
#define __gnu_java_security_hash_RipeMD160__

#pragma interface

#include <gnu/java/security/hash/BaseHash.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace java
    {
      namespace security
      {
        namespace hash
        {
          class RipeMD160;
        }
      }
    }
  }
}

class gnu::java::security::hash::RipeMD160 : public ::gnu::java::security::hash::BaseHash
{
public:
  RipeMD160 ();
private:
  RipeMD160 (::gnu::java::security::hash::RipeMD160 *);
public:
  virtual ::java::lang::Object *clone ();
public:  // actually protected
  virtual void transform (jbyteArray, jint);
  virtual jbyteArray padBuffer ();
  virtual jbyteArray getResult ();
  virtual void resetContext ();
public:
  virtual jboolean selfTest ();
private:
  static const jint BLOCK_SIZE = 64L;
  static ::java::lang::String *DIGEST0;
  static jintArray R;
  static jintArray Rp;
  static jintArray S;
  static jintArray Sp;
  static ::java::lang::Boolean *valid;
  jint __attribute__((aligned(__alignof__( ::gnu::java::security::hash::BaseHash ))))  h0;
  jint h1;
  jint h2;
  jint h3;
  jint h4;
  jintArray X;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_java_security_hash_RipeMD160__ */
