// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __java_awt_image_RescaleOp__
#define __java_awt_image_RescaleOp__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace java
  {
    namespace awt
    {
      namespace geom
      {
        class Point2D;
        class Rectangle2D;
      }
      namespace image
      {
        class RescaleOp;
        class ColorModel;
        class WritableRaster;
        class Raster;
        class BufferedImage;
      }
      class RenderingHints;
    }
  }
}

class java::awt::image::RescaleOp : public ::java::lang::Object
{
public:
  RescaleOp (jfloatArray, jfloatArray, ::java::awt::RenderingHints *);
  RescaleOp (jfloat, jfloat, ::java::awt::RenderingHints *);
  virtual jfloatArray getScaleFactors (jfloatArray);
  virtual jfloatArray getOffsets (jfloatArray);
  virtual jint getNumFactors ();
  virtual ::java::awt::RenderingHints *getRenderingHints () { return hints; }
  virtual ::java::awt::image::BufferedImage *filter (::java::awt::image::BufferedImage *, ::java::awt::image::BufferedImage *);
  virtual ::java::awt::image::WritableRaster *filter (::java::awt::image::Raster *, ::java::awt::image::WritableRaster *);
  virtual ::java::awt::image::BufferedImage *createCompatibleDestImage (::java::awt::image::BufferedImage *, ::java::awt::image::ColorModel *);
  virtual ::java::awt::image::WritableRaster *createCompatibleDestRaster (::java::awt::image::Raster *);
  virtual ::java::awt::geom::Rectangle2D *getBounds2D (::java::awt::image::BufferedImage *);
  virtual ::java::awt::geom::Rectangle2D *getBounds2D (::java::awt::image::Raster *);
  virtual ::java::awt::geom::Point2D *getPoint2D (::java::awt::geom::Point2D *, ::java::awt::geom::Point2D *);
private:
  jfloatArray __attribute__((aligned(__alignof__( ::java::lang::Object ))))  scale;
  jfloatArray offsets;
  ::java::awt::RenderingHints *hints;
public:

  static ::java::lang::Class class$;
};

#endif /* __java_awt_image_RescaleOp__ */
