// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_print_attribute_standard_JobMediaSheetsSupported__
#define __javax_print_attribute_standard_JobMediaSheetsSupported__

#pragma interface

#include <javax/print/attribute/SetOfIntegerSyntax.h>

extern "Java"
{
  namespace javax
  {
    namespace print
    {
      namespace attribute
      {
        namespace standard
        {
          class JobMediaSheetsSupported;
        }
      }
    }
  }
}

class javax::print::attribute::standard::JobMediaSheetsSupported : public ::javax::print::attribute::SetOfIntegerSyntax
{
public:
  JobMediaSheetsSupported (jint, jint);
  virtual jboolean equals (::java::lang::Object *);
  virtual ::java::lang::Class *getCategory ();
  virtual ::java::lang::String *getName ();
private:
  static const jlong serialVersionUID = 2953685470388672940LL;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_print_attribute_standard_JobMediaSheetsSupported__ */
