// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_print_attribute_standard_JobStateReasons__
#define __javax_print_attribute_standard_JobStateReasons__

#pragma interface

#include <java/util/HashSet.h>

extern "Java"
{
  namespace javax
  {
    namespace print
    {
      namespace attribute
      {
        namespace standard
        {
          class JobStateReasons;
        }
      }
    }
  }
}

class javax::print::attribute::standard::JobStateReasons : public ::java::util::HashSet
{
public:
  JobStateReasons ();
  JobStateReasons (jint, jfloat);
  JobStateReasons (jint);
  JobStateReasons (::java::util::Collection *);
  virtual jboolean add (::java::lang::Object *);
  virtual ::java::lang::Class *getCategory ();
  virtual ::java::lang::String *getName ();
private:
  static const jlong serialVersionUID = 8849088261264331812LL;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_print_attribute_standard_JobStateReasons__ */
