// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_print_attribute_standard_PrinterMoreInfo__
#define __javax_print_attribute_standard_PrinterMoreInfo__

#pragma interface

#include <javax/print/attribute/URISyntax.h>

extern "Java"
{
  namespace javax
  {
    namespace print
    {
      namespace attribute
      {
        namespace standard
        {
          class PrinterMoreInfo;
        }
      }
    }
  }
  namespace java
  {
    namespace net
    {
      class URI;
    }
  }
}

class javax::print::attribute::standard::PrinterMoreInfo : public ::javax::print::attribute::URISyntax
{
public:
  PrinterMoreInfo (::java::net::URI *);
  virtual jboolean equals (::java::lang::Object *);
  virtual ::java::lang::Class *getCategory ();
  virtual ::java::lang::String *getName ();
private:
  static const jlong serialVersionUID = 4555850007675338574LL;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_print_attribute_standard_PrinterMoreInfo__ */
