// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_print_CancelablePrintJob__
#define __javax_print_CancelablePrintJob__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace print
    {
      class CancelablePrintJob;
    }
  }
}

class javax::print::CancelablePrintJob : public ::java::lang::Object
{
public:
  virtual void cancel () = 0;

  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif /* __javax_print_CancelablePrintJob__ */
