// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __gnu_javax_net_ssl_provider_DigestOutputStream__
#define __gnu_javax_net_ssl_provider_DigestOutputStream__

#pragma interface

#include <java/io/FilterOutputStream.h>
#include <gcj/array.h>

extern "Java"
{
  namespace gnu
  {
    namespace javax
    {
      namespace net
      {
        namespace ssl
        {
          namespace provider
          {
            class DigestOutputStream;
          }
        }
      }
    }
    namespace java
    {
      namespace security
      {
        namespace hash
        {
          class IMessageDigest;
        }
      }
    }
  }
}

class gnu::javax::net::ssl::provider::DigestOutputStream : public ::java::io::FilterOutputStream
{
public: // actually package-private
  DigestOutputStream (::java::io::OutputStream *, ::gnu::java::security::hash::IMessageDigest *, ::gnu::java::security::hash::IMessageDigest *);
  virtual void setDigesting (jboolean);
public:
  virtual void write (jint);
  virtual void write (jbyteArray);
  virtual void write (jbyteArray, jint, jint);
private:
  ::gnu::java::security::hash::IMessageDigest * __attribute__((aligned(__alignof__( ::java::io::FilterOutputStream )))) md5;
  ::gnu::java::security::hash::IMessageDigest *sha;
  jboolean digesting;
public:

  static ::java::lang::Class class$;
};

#endif /* __gnu_javax_net_ssl_provider_DigestOutputStream__ */
